### ISSUE TITLE
Visual feedback for damage dealt

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#11]
In a big, bold font right next to the enemy... you know, it's part of the enjoyment in this kind of games.

**Comment by Vonathar** [comment]
As always, I can't thank you enough for pointing all of these out - visual feedback for damage dealt will be added in 1.4.4!

**Comment by Vonathar** [comment]
As always, I can't thank you enough for pointing all of these out - visual feedback for damage dealt will be added soon !
