### ISSUE TITLE
Show skill effect on click damage and pet dps

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#15]
As of now (in div#userInterface-topSummary-div):
- skill 4's click damage increase is shown silently, in the same font
- skill 2's pet dps increase is not shown at all

Proposal:
- show both, and in a visually satisfying way (i.e. either the total in bold, or base + increase, in bold)

**Comment by Vonathar** [comment]
Thank you for the idea @xalexalex - this is going to be added soon in Fantasia! Please keep up forwarding all your great suggestions.
