### ISSUE TITLE
Maxing out quests doesn't work as expected

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#18]
After maxing out a quest, it remains active:
![image](https://user-images.githubusercontent.com/16612842/58767527-b16ae880-858c-11e9-89a2-ec39cf667c5e.png)
and it keeps giving AP every time an action of that kind is performed (in this case, on each pet attack):
![image](https://user-images.githubusercontent.com/16612842/58767530-b9c32380-858c-11e9-9dec-f53939ffe181.png)

**Comment by Vonathar** [comment]
Thank you kindly for finding this bug and taking the time to share it - it will be fixed in 1.4.6.
