### ISSUE TITLE
There is no debug/cheat mode

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#19]
Which could be useful for testing.
Suggestions:
- clearly show that it is active in the stats window and perhaps with a watermark in a corner or on the background
- either hotkeys or buttons/textboxes in a div as the interface
- ability to add at least basic variables (i.e. experience and coins)

**Comment by Vonathar** [comment]
Thank you kindly, this is a great idea to make the entire testing progress much more efficient - I pushed an implementation of your idea in 1.4.7!
