### ISSUE TITLE
Suggestion: Item pop-up

### ISSUE THREAD

**Issue by Mahonaki** [Vonathar/fantasia-js#24]
When clicking on an items within inventory, the information box of the selected item stays until it is clicked again. I think it would be easier/faster for players if the information box would disappear when the mouse is hovered off the item or it's info box.

**Comment by Vonathar** [comment]
Thank you kindly @Mahonaki for pointing this out! As @xalexalex mentioned in the issue #27 , as there seems to be a few ongoing issues with the inventory UX, please refer all similar issues in the other one. Again, thank you for the suggestion - it will be added in the future versions of Fantasia!
