### ISSUE TITLE
suggestion: make pet damage a bit more random and smoother

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#31]
i.e. not at predefined ticks, and always together and always the same

ideas:
- make each pet attack separately (this would already make it smoother)
- make each pet attack at a slightly variable interval (e.g. a random value between 90% and 110% of the current interval)

open to suggestions/ideas!

**Comment by Vonathar** [comment]
Thank you kindly @xalexalex , it does indeed feel too mechanic as it is currently - your idea would be very helpful in this regard. It is going to be added soon!
