### ISSUE TITLE
it is not clear when a critical hit is landed

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#32]
With 20% crit chance I haven't been able to land a critical hit. Or maybe I did but it wasn't shown in the damage popup.
Suggestion: show the critical damage in the damage popup, possibly in a way that stands out from normal hits. You may even want to consider making the enemy tremble, play a particular sound effect, or something like that.

**Comment by Vonathar** [comment]
Thank you for that @xalexalex , I agree with you that in the current state it is not clear at all as to whether the hit is critical or double; a fix for that will be added in 1.8.7. Thank you again, and feel free to mention anything else you have in mind!
