### ISSUE TITLE
The tutorial in the battle log is not easy to peruse

### ISSUE THREAD

**Issue by xalexalex** [Vonathar/fantasia-js#9]
It's hard to read because it gets scrolled for every new line added. It could be shown in a separate, temporary area.
Maybe, with a button somewhere that shows/hides it, it can also be used as a reference for hotkeys.

**Comment by Vonathar** [comment]
Thank you for the great suggestion - it will be implemented in 1.5.0, with a tutorial which will be rendered in a separate div. As always, thanks for pointing it out @xalexalex !
